//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatiFren.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageDetail
    {
        public int PageDetail_ID { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public string SeoKeywords { get; set; }
        public string SeoDescription { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual Page Page { get; set; }
    }
}
